export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS ="GET_DATA_SUCCESS";
export const GET_DATA_FAILED ="GET_DATA_FAILED";

export const DELETE_TABLE_REQUEST = "DELETE_TABLE_REQUEST";
export const DELETE_TABLE_SUCCESS = "DELETE_TABLE_SUCCESS";
export const DELETE_TABLE_FAILED = "DELETE_TABLE_FAILED";

export const POST_DETAIL_REQUEST="POST_DETAIL_REQUEST";
export const POST_DETAIL_SUCCESS="POST_DETAIL_SUCCESS";
export const POST_DETAIL_FAILED = "POST_DETAIL_FAILED";
